#!/usr/bin/python
#	vim:fileencoding=utf-8
# Create merged 'package.mask' file and maintain 'package.unmask' using it
# (C) 2010 Michał Górny, distributed under the terms of 2-clause BSD license

import sys

try:
	from flaggie.cli import main
except ImportError:
	import os.path
	sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'lib'))
	# Ensure a clean reload from the new location.
	if 'flaggie' in sys.modules:
		try: # py3 compat
			from imp import reload
		except ImportError:
			pass

		reload(sys.modules['flaggie'])
		del sys.modules['flaggie']
	from flaggie.cli import main

if __name__ == '__main__':
	sys.exit(main(sys.argv))
